name: SmartOrb CI/CD
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npx hardhat compile
      - run: npx hardhat test

      - name: 🚀 Deploy to Smart Orb
        run: npx hardhat run hardhat/deploy.js --network smartorb
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          SMART_ORB_RPC: https://rpc.smartorb.network
          SMART_ORB_EXPLORER_API_KEY: ${{ secrets.SMART_ORB_EXPLORER_API_KEY }}

      - name: 🧪 Deploy to Sepolia (Backup)
        run: npx hardhat run hardhat/deploy.js --network sepolia
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          ALCHEMY_API_KEY: ${{ secrets.ALCHEMY_API_KEY }}
          ETHERSCAN_API_KEY: ${{ secrets.ETHERSCAN_API_KEY }}
